{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "graph",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "graph-1.0.2.aar",
          "url": "graph-1.0.2.aar",
          "size": 2251759,
          "sha512": "8df0883103c88708c2042161befcf78f5bb2ce5ae09e6566bf7b47c6f29a0132b183f1c6d1c1ad60e5460e013b2d52ccdc03be34623758aad6b03c2c80bdff98",
          "sha256": "e61830b49f83facf08298afb8ffc00e15a9bb3f3bc657d8c97b87b2d1c81cb8b",
          "sha1": "02840c43475673a3df47571f948cfe5897fb0ee2",
          "md5": "e3713e28f9c9c04c3a800b622f9d1ff1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "graph-1.0.2.aar",
          "url": "graph-1.0.2.aar",
          "size": 2251759,
          "sha512": "8df0883103c88708c2042161befcf78f5bb2ce5ae09e6566bf7b47c6f29a0132b183f1c6d1c1ad60e5460e013b2d52ccdc03be34623758aad6b03c2c80bdff98",
          "sha256": "e61830b49f83facf08298afb8ffc00e15a9bb3f3bc657d8c97b87b2d1c81cb8b",
          "sha1": "02840c43475673a3df47571f948cfe5897fb0ee2",
          "md5": "e3713e28f9c9c04c3a800b622f9d1ff1"
        }
      ]
    }
  ]
}
