{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "fullpanels",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "pinger",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "graph",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "lights",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-1.0.6.aar",
          "url": "fullpanels-1.0.6.aar",
          "size": 90964,
          "sha512": "9ea30e4a9ddc0cea28a4f9da1c9afdebaa6ac2a8c09643bf58fc3f1258c9f797b3c873ffdc855b1c4497c1c258b96833707f7816e93eb09c33aedc1e80866a16",
          "sha256": "8b86135ab3cbcb56cb5123b36ba8ac52468c7f2d801716cc2f69374e17f1d70e",
          "sha1": "fbc979d298ff00919055441df88f65bc8a9038ac",
          "md5": "d84a5ae72b905a1a523876d569176d51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "pinger",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "graph",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "lights",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-1.0.6.aar",
          "url": "fullpanels-1.0.6.aar",
          "size": 90964,
          "sha512": "9ea30e4a9ddc0cea28a4f9da1c9afdebaa6ac2a8c09643bf58fc3f1258c9f797b3c873ffdc855b1c4497c1c258b96833707f7816e93eb09c33aedc1e80866a16",
          "sha256": "8b86135ab3cbcb56cb5123b36ba8ac52468c7f2d801716cc2f69374e17f1d70e",
          "sha1": "fbc979d298ff00919055441df88f65bc8a9038ac",
          "md5": "d84a5ae72b905a1a523876d569176d51"
        }
      ]
    }
  ]
}
