{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-1.0.2.aar",
          "url": "battery-1.0.2.aar",
          "size": 368988,
          "sha512": "386a5330e92f79048929f389911ec64c4c9eaaa81a7e51e3e0e6714ea63789907d110759d76498c1080aab4718e2888a078c5cfb2cd4d298490e09b438ee4718",
          "sha256": "5b29c3913171e9af871cc460447af9ce50b227a76fa1dfd5adcfb57a8c09015f",
          "sha1": "c8080a6955ccd4f2e0d41560541bb18708fdb008",
          "md5": "1823ebc5dacf19847d877588f91389fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-1.0.2.aar",
          "url": "battery-1.0.2.aar",
          "size": 368988,
          "sha512": "386a5330e92f79048929f389911ec64c4c9eaaa81a7e51e3e0e6714ea63789907d110759d76498c1080aab4718e2888a078c5cfb2cd4d298490e09b438ee4718",
          "sha256": "5b29c3913171e9af871cc460447af9ce50b227a76fa1dfd5adcfb57a8c09015f",
          "sha1": "c8080a6955ccd4f2e0d41560541bb18708fdb008",
          "md5": "1823ebc5dacf19847d877588f91389fd"
        }
      ]
    }
  ]
}
