{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-1.0.5.aar",
          "url": "telemetry-1.0.5.aar",
          "size": 90404,
          "sha512": "02162948d7c66e81d9642ea5ec5602a91030ee9a1504541c41a05ce39b1894e27be2f99e9395079aa1d72fdccfb16bca58315e2bd109b915884229efb0677258",
          "sha256": "0835160f2668fc3ffed7ec397b75a0924cca3749af125518a13495bdb04a121d",
          "sha1": "9eccd9521ab9d68059c2a9893570810364e1e6f9",
          "md5": "57312eba424e80236a34e6b61c37b06b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-1.0.5.aar",
          "url": "telemetry-1.0.5.aar",
          "size": 90404,
          "sha512": "02162948d7c66e81d9642ea5ec5602a91030ee9a1504541c41a05ce39b1894e27be2f99e9395079aa1d72fdccfb16bca58315e2bd109b915884229efb0677258",
          "sha256": "0835160f2668fc3ffed7ec397b75a0924cca3749af125518a13495bdb04a121d",
          "sha1": "9eccd9521ab9d68059c2a9893570810364e1e6f9",
          "md5": "57312eba424e80236a34e6b61c37b06b"
        }
      ]
    }
  ]
}
