{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-1.0.3.aar",
          "url": "configurables-1.0.3.aar",
          "size": 520022,
          "sha512": "9f83fcf111fbb8f9c2b6b7ef2b95c81deed6930f2e64cf279033cf6db2428105f2c68d53787289f7a401d61848c4b73bab36c7ffb650e0ffd98807c68a0ad034",
          "sha256": "8a9ddc76691f46e93d873e57ef318a17cf1c2714ae75b9d2e801cbdaf3f67a7e",
          "sha1": "411723394b5056b89e845e9805eb8fa977af1e88",
          "md5": "b835887eafaa7e9e22c0ca73b7ebe161"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-1.0.3.aar",
          "url": "configurables-1.0.3.aar",
          "size": 520022,
          "sha512": "9f83fcf111fbb8f9c2b6b7ef2b95c81deed6930f2e64cf279033cf6db2428105f2c68d53787289f7a401d61848c4b73bab36c7ffb650e0ffd98807c68a0ad034",
          "sha256": "8a9ddc76691f46e93d873e57ef318a17cf1c2714ae75b9d2e801cbdaf3f67a7e",
          "sha1": "411723394b5056b89e845e9805eb8fa977af1e88",
          "md5": "b835887eafaa7e9e22c0ca73b7ebe161"
        }
      ]
    }
  ]
}
